FROM centos
RUN yum install python36 -y
RUN yum install python3-pip -y
RUN pip3 install numpy
RUN pip3 install pandas
RUN pip3 install --upgrade pip
RUN pip3 install scikit-learn
RUN yum install httpd -y

