FROM centos
RUN yum install python36 -y
RUN yum install python3-pip -y
RUN pip3 install numpy
RUN pip3 install pandas
RUN pip3 install --upgrade pip
RUN pip3 install tensorflow
RUN pip3 install keras
RUN pip3 install matplotlib==3.0.3
RUN pip3 install scikit-learn
RUN yum install python3-tkinter -y
RUN yum install httpd -y

